CREATE DATABASE tokenDB;

USE tokenDB;

CREATE TABLE TempTokens (address VARCHAR(255) PRIMARY KEY, name VARCHAR(255), symbol VARCHAR(255), decimals INT, chain VARCHAR(40), price DECIMALS(30,10), logoURL VARCHAR(1024));